---
name: HTML-Form-XSS
version: 0.1
author:
  - 'MacGyveR <dumb@cpan.org>'
abstract: Test HTML forms for cross site scripting vulnerabilities.
license: perl
requires:
  Carp: ""
  Data::Dumper: ""
build_requires:
  HTML::Form: ""
  Test::More: ""
  WWW::Mechanize: ""
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  DT::XSSLint::Result:
    file: lib/HTML/Form/XSS/Result.pm
  HTML::Form::XSS:
    file: lib/HTML/Form/XSS.pm
    version: 0.1
resources:
  license: http://dev.perl.org/licenses/
